/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health-check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация по токену регистрации
         * @description Создаёт аккаунт только при валидном токене регистрации (FR A1).
         *     Без/невалидный токен → 403 (Gherkin §1 «Регистрация без токена запрещена»).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Аккаунт создан */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
                /** @description Имя пользователя занято */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Логин
         * @description Выдаёт access (JWT, короткоживущий) и refresh (непрозрачный). FR A3.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Токены выданы */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обновление токенов
         * @description Меняет валидный refresh на новую пару (ротация refresh). FR A3.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description Новая пара токенов */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Выход (отзыв refresh)
         * @description Отзывает refresh-токен. FR A3.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description Выполнено */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/registration-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Показать действующий токен регистрации
         * @description Доступно только администратору (FR A2, Gherkin §1 «Администратор видит токен»).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Действующий токен */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token?: string;
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список интеграций пользователя
         * @description Только свои интеграции (FR A4, I3). Содержит статус онлайн/оффлайн (FR B4).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Integration"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Создать интеграцию (выдаёт UUID)
         * @description Обязательное имя, опциональный IP-хинт (FR B1). В ответе — секретный UUID,
         *     доступный пользователю для настройки машины (FR B2, Gherkin §2 «Создание выдаёт UUID»).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IntegrationCreate"];
                };
            };
            responses: {
                /** @description Создана */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IntegrationWithSecret"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Получить интеграцию */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Интеграция */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IntegrationWithSecret"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Удалить интеграцию
         * @description При наличии активных задач требует подтверждения (?confirm=true) и корректно
         *     завершает/отменяет их (FR B5, Gherkin §2 «Удаление требует подтверждения»).
         */
        delete: {
            parameters: {
                query?: {
                    confirm?: boolean;
                };
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Удалено */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Есть активные задачи, нужно подтверждение (confirm=true) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Редактировать имя/IP
         * @description Не прерывает активные задачи (FR B5, Gherkin §2).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IntegrationUpdate"];
                };
            };
            responses: {
                /** @description Обновлено */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * История задач
         * @description Состав записи — FR H1, Gherkin §10. Хранение бессрочно (FR I2).
         */
        get: {
            parameters: {
                query?: {
                    integration_id?: string;
                    status?: components["schemas"]["TaskStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список задач */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Поставить задачу
         * @description Ставит задачу в очередь к машине (FR E1). Дедуп по заголовку Idempotency-Key
         *     (FR E7, Gherkin §4 «Защита от двойной отправки»). Если машина оффлайн — задача
         *     ждёт в очереди (FR E4, Gherkin §9).
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Ключ дедупликации постановки задачи (FR E7). */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskCreate"];
                };
            };
            responses: {
                /** @description Идемпотентный повтор — возвращена уже созданная задача */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Задача создана (status=queued) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /** Карточка задачи */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Задача */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        /**
         * Журнал событий задачи
         * @description Вопросы агента, ответы пользователя, согласования, смены статуса (FR H1, аудит F4).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Упорядоченный журнал */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskEvent"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ответить на вопрос агента
         * @description Ответ привязывается к конкретному question_id (FR F2, Gherkin §5
         *     «Несколько вопросов сопоставляются корректно»). После ответа задача → running.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        question_id: string;
                        text: string;
                    };
                };
            };
            responses: {
                /** @description Ответ принят */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Согласовать/отклонить команду
         * @description Решение по запросу согласования команды вне allowlist (FR F3, Gherkin §5
         *     «Команда вне allowlist», «Отклонение команды»).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        request_id: string;
                        /** @enum {string} */
                        decision: "approve" | "reject";
                    };
                };
            };
            responses: {
                /** @description Решение принято */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Отменить задачу
         * @description Команда отмены гарантированно доходит до машины, агент останавливается (FR E6,
         *     Gherkin §8). Приоритет — сохранность данных: критическая операция доводится
         *     до безопасного состояния, мгновенная остановка не гарантируется.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Отмена инициирована */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Подтвердить завершение
         * @description Переводит задачу из awaiting_confirm в completed. ТОЛЬКО это действие закрывает
         *     задачу (FR E2, Gherkin §7 «Пользователь подтверждает завершение»).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Задача завершена */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Отклонить результат (на доработку)
         * @description Из awaiting_confirm возвращает задачу в running (FR E2, Gherkin §7).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["IdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description Возвращена в работу */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/telegram/link-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Сгенерировать код привязки Telegram
         * @description Web генерирует одноразовый код; пользователь отправляет /start <code> боту,
         *     который обменивает его на привязку (FR D3).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Код создан */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: string;
                            /** Format: date-time */
                            expires_at?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/telegram/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обменять код привязки на привязку Telegram-аккаунта
         * @description Вызывается ботом (тикет 10.2) при обработке `/start <code>`: обменивает
         *     одноразовый код (выданный `POST /channels/telegram/link-code`, тикет 9.6) на
         *     привязку telegram_user_id ↔ user_id (FR D3, Gherkin §6). Без Bearer — в этой
         *     точке пользователь ещё не аутентифицирован в системе как web-клиент; вместо
         *     этого доказательством права на привязку служит сам одноразовый код —
         *     высокоэнтропийный, одноразовый, с ограниченным сроком жизни (та же модель
         *     доверия, что у registration_token в POST /auth/register). Код атомарно
         *     помечается использованным ТОЛЬКО при успешной привязке (одна транзакция) —
         *     на любой ошибке код остаётся в прежнем состоянии (кроме случаев, когда сама
         *     ошибка — «код уже использован» или «код истёк»), т.е. неудачная попытка
         *     (например конфликт already-linked) не сжигает код впустую.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChannelLinkRequest"];
                };
            };
            responses: {
                /** @description Аккаунт привязан */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChannelLink"];
                    };
                };
                /** @description Некорректное тело запроса */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Код привязки не найден */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Код уже использован, истёк, либо этот telegram_user_id уже привязан к другому аккаунту — см. поле code в теле ошибки. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/telegram/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обменять telegram_user_id на короткоживущий acting-токен (внутренний, только для бота)
         * @description Действия из Telegram — постановка/отмена задачи, ответ на вопрос агента
         *     (тикет 10.3, FR D1, §4 «Постановка задачи из канала») — должны выполняться
         *     через ТОТ ЖЕ REST API, что и web (принцип «единый API»,
         *     docs/01_tech_stack_and_architecture.md). У бота нет пользовательского
         *     access-JWT (только telegram_user_id отправителя апдейта), поэтому вместо
         *     Bearer этот эндпоинт аутентифицируется общим сервисным секретом в
         *     заголовке X-Bot-Service-Secret (ORCH_BOT_SERVICE_SECRET у оркестратора,
         *     BOT_SERVICE_SECRET у бота — одно и то же значение, известное только двум
         *     сервисам; см. docs/MANUAL_STEPS.md). Это доверенный внутренний канал:
         *     оркестратор доступен боту напрямую внутри docker compose-сети
         *     (BOT_ORCHESTRATOR_URL, тикет 10.2), минуя Caddy и публичный интернет.
         *     При валидном секрете telegram_user_id резолвится в user_id через
         *     channel_links (FR D3, тикет 10.2) и выпускается ОБЫЧНЫЙ access-JWT (тот
         *     же формат/TTL, что и POST /auth/login, FR A3). Дальше бот выполняет
         *     постановку/отмену задачи и ответ на вопрос ЧЕРЕЗ ОБЫЧНЫЕ защищённые
         *     операции контракта (POST /tasks, /tasks/{id}/cancel, /tasks/{id}/answer,
         *     GET /integrations) с этим токеном как Bearer — у оркестратора нет и не
         *     появляется отдельного пути постановки задачи «для Telegram».
         *     telegram_user_id, не привязанный ни к одному аккаунту (пользователь ещё
         *     не выполнил `/start <code>`), → 404: бот отвечает пользователю подсказкой
         *     привязать аккаунт (см. bot/README.md).
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "X-Bot-Service-Secret": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TelegramActingTokenRequest"];
                };
            };
            responses: {
                /** @description Acting-токен выдан */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TelegramActingToken"];
                    };
                };
                /** @description Некорректное тело запроса */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Неверный/отсутствующий X-Bot-Service-Secret */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description telegram_user_id не привязан ни к одному аккаунту */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/machine/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Точка подключения агента (WebSocket Upgrade)
         * @description Агент устанавливает исходящее WS-соединение и аутентифицируется по UUID интеграции
         *     (FR B3). Все команды/события идут асинхронно через шину (FR §7). Формат сообщений —
         *     docs/protocol.md. Это не обычный REST-эндпоинт.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Switching Protocols (WebSocket) */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Точка подключения браузера (WebSocket Upgrade)
         * @description Открытая вкладка web держит исходящее WS-соединение к оркестратору и
         *     аутентифицируется по access-токену (FR G1). Уведомления (например, "агент
         *     задал вопрос") доставляются в открытую вкладку без перезагрузки страницы
         *     (§6 «Уведомление в web по WebSocket»). Формат сообщений — простой JSON,
         *     НЕ конверт машинного протокола docs/protocol.md; это не обычный
         *     REST-эндпоинт.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Switching Protocols (WebSocket) */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        RegisterRequest: {
            registration_token: string;
            username: string;
            /** Format: password */
            password: string;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            /** @description TTL access-токена */
            expires_in?: number;
        };
        IntegrationCreate: {
            name: string;
            /** @description Опциональная доп. проверка IP (FR B3) */
            ip_hint?: string | null;
        };
        IntegrationUpdate: {
            name?: string;
            ip_hint?: string | null;
        };
        Integration: {
            /** Format: uuid */
            id?: string;
            name?: string;
            ip_hint?: string | null;
            /**
             * @description FR B4
             * @enum {string}
             */
            status?: "online" | "offline";
            /** Format: date-time */
            last_seen_at?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        IntegrationWithSecret: components["schemas"]["Integration"] & {
            /**
             * Format: uuid
             * @description Секрет для аутентификации машины (FR B2). Показывается владельцу.
             */
            uuid?: string;
        };
        /**
         * @description Статусы FSM, см. docs/Жизненный цикл задачи.md
         * @enum {string}
         */
        TaskStatus: "created" | "queued" | "running" | "waiting_user" | "awaiting_confirm" | "completed" | "failed" | "cancelled" | "stale";
        TaskCreate: {
            /** Format: uuid */
            integration_id: string;
            /** @description Текст запроса. Неизменяем после создания задачи (FR H3) — API для редактирования текста существующей задачи нет. Чтобы «исправить» уже отправленный запрос, нужно создать новую задачу отдельным POST /tasks (свой Idempotency-Key) — это отдельное действие («повтор»), не затрагивающее статус/журнал уже существующей задачи. */
            text: string;
        };
        Task: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            integration_id?: string;
            /** @description Текст запроса на момент создания задачи; неизменяем (FR H3). */
            text?: string;
            status?: components["schemas"]["TaskStatus"];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /** @description Элемент журнала задачи (FR H1, аудит F4) */
        TaskEvent: {
            /** Format: uuid */
            id?: string;
            /** @description Порядковый номер в рамках задачи */
            seq?: number;
            /** @enum {string} */
            type?: "status_change" | "agent_question" | "user_answer" | "command_approval_request" | "user_decision" | "agent_progress" | "agent_completed" | "error";
            payload?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
        };
        /** @description Тело POST /channels/telegram/link (FR D3, тикет 10.2). */
        ChannelLinkRequest: {
            /** @description Одноразовый код привязки из POST /channels/telegram/link-code (тикет 9.6). */
            code: string;
            /** @description Telegram user id отправителя /start <code> (числовой id Telegram, передаётся строкой — channel_links.external_id хранит идентификатор как TEXT, канало-агностично). */
            telegram_user_id: string;
        };
        /** @description Привязка внешнего канала к аккаунту (FR D3). */
        ChannelLink: {
            /** @enum {string} */
            channel?: "telegram";
            /** @description telegram_user_id привязанного Telegram-аккаунта */
            external_id?: string;
            /** Format: date-time */
            created_at?: string;
        };
        /** @description Тело POST /channels/telegram/token (FR D1, тикет 10.3). */
        TelegramActingTokenRequest: {
            /** @description Telegram user id отправителя апдейта (та же строка, что и в ChannelLinkRequest). */
            telegram_user_id: string;
        };
        /** @description Короткоживущий access-JWT, действующий от имени пользователя, к которому привязан telegram_user_id (FR D1, тикет 10.3). Тот же формат и TTL, что и access-токен POST /auth/login (FR A3) — используется боту как Bearer в дальнейших вызовах единого API. */
        TelegramActingToken: {
            access_token?: string;
            /** Format: date-time */
            expires_at?: string;
        };
    };
    responses: {
        /** @description Не аутентифицирован */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Запрещено */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Не найдено */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        IdPath: string;
        /** @description Ключ дедупликации постановки задачи (FR E7). */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
