// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bootstrap.sql

package db

import (
	"context"
)

const bootstrapPing = `-- name: BootstrapPing :one

SELECT 1 AS ok
`

// bootstrap.sql — единственный «затравочный» запрос для sqlc (тикет 0.2).
//
// Назначение (тех): sqlc v1.27.0 завершается ошибкой, если каталог queries пуст
// («no queries contained in paths»). Бизнес-запросы добавит тикет 1.1; до тех пор
// этот тривиальный health-запрос нужен, чтобы `make generate` (sqlc) отрабатывал
// и генерил orchestrator/internal/db/models.go из схемы миграций.
//
// Запрос не обращается к таблицам (SELECT 1) и удалится/заменится в 1.1.
func (q *Queries) BootstrapPing(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, bootstrapPing)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
