// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: refresh_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, revoked, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// refresh_tokens.sql — запросы непрозрачных refresh-токенов (FR A3).
//
// Назначение (бизнес): refresh/logout-поток (FR A3). Храним только ХЭШ токена
// (sha-256/HMAC), сам токен не персистится; сверка и хэширование — в сервисном
// слое (тикеты 1.3/1.7). Эти запросы — слой данных: вставка, поиск по хэшу, отзыв.
// Схема — orchestrator/migrations/00001_users_and_auth.sql (не редактируется).
// Сохраняет выданный refresh-токен (хэш, владелец, срок). token_hash уникален.
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, revoked, expires_at, created_at FROM refresh_tokens
WHERE token_hash = $1
`

// Находит токен по хэшу — для валидации при refresh (проверку revoked/expires_at
// делает сервисный слой; FR A3).
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens
SET revoked = TRUE
WHERE user_id = $1
`

// Отзывает все токены пользователя (logout со всех устройств / смена пароля; FR A3).
func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, userID)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE refresh_tokens
SET revoked = TRUE
WHERE token_hash = $1
`

// Отзывает конкретный токен по хэшу (logout текущей сессии; FR A3).
func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByHash, tokenHash)
	return err
}
