// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: registration_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRegistrationToken = `-- name: CreateRegistrationToken :one

INSERT INTO registration_tokens (token)
VALUES ($1)
RETURNING id, token, is_active, created_at
`

// registration_tokens.sql — запросы секретного токена регистрации (FR A1, A2).
//
// Назначение (бизнес): регистрация закрыта и идёт только по активному токену
// (FR A1); токен виден администратору в plaintext (FR A2). В MVP — один активный
// токен, без ротации/срока. Эти запросы — слой данных под тикеты 1.2/1.6; сверку
// предъявленного токена с активным делает сервисный слой.
// Схема — orchestrator/migrations/00001_users_and_auth.sql (не редактируется).
// Создаёт активный токен регистрации (token — секрет, генерируется в сервисе).
func (q *Queries) CreateRegistrationToken(ctx context.Context, token string) (RegistrationToken, error) {
	row := q.db.QueryRow(ctx, createRegistrationToken, token)
	var i RegistrationToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateRegistrationToken = `-- name: DeactivateRegistrationToken :exec
UPDATE registration_tokens
SET is_active = FALSE
WHERE id = $1
`

// Деактивирует токен по id (ротация/отзыв) — переводит is_active в FALSE.
func (q *Queries) DeactivateRegistrationToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateRegistrationToken, id)
	return err
}

const getActiveRegistrationToken = `-- name: GetActiveRegistrationToken :one
SELECT id, token, is_active, created_at FROM registration_tokens
WHERE is_active = TRUE
ORDER BY created_at DESC
LIMIT 1
`

// Текущий активный токен — для проверки при регистрации (FR A1) и показа админу
// (FR A2). В MVP активный токен один; берём самый свежий на случай инвариант-сбоя.
func (q *Queries) GetActiveRegistrationToken(ctx context.Context) (RegistrationToken, error) {
	row := q.db.QueryRow(ctx, getActiveRegistrationToken)
	var i RegistrationToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
