// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, integration_id, text_enc, idempotency_key)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, integration_id, text_enc, status, idempotency_key, created_at, updated_at
`

type CreateTaskParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	IntegrationID  pgtype.UUID `json:"integration_id"`
	TextEnc        []byte      `json:"text_enc"`
	IdempotencyKey *string     `json:"idempotency_key"`
}

// Вставляет новую задачу СО СТАТУСОМ ПО УМОЛЧАНИЮ 'created' (схема,
// migrations/00003) — переход в 'queued' и запись task_events(status_change)
// выполняются ОТДЕЛЬНО, сразу после вставки, через
// task.Transitioner.Transition(ctx, id, task.TriggerEnqueued): тикет 5.2
// сделал Transitioner единственной точкой смены tasks.status, поэтому
// обработчик POST /tasks (тикет 5.3) не пишет 'queued'/task_events напрямую.
// Коллизия (user_id, idempotency_key) — SQLSTATE 23505 (uq_tasks_idempotency);
// обработчик отвечает 409 (полноценное «вернуть существующую задачу, 200» —
// отдельный тикет 5.5).
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.IntegrationID,
		arg.TextEnc,
		arg.IdempotencyKey,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IntegrationID,
		&i.TextEnc,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskStatusForUpdate = `-- name: GetTaskStatusForUpdate :one

SELECT status FROM tasks WHERE id = $1 FOR UPDATE
`

// tasks.sql — запросы FSM задач (тикет 5.2, FR E1).
//
// Назначение (бизнес): единственная точка смены tasks.status — функция
// Transition (orchestrator/internal/task/transition.go). Эти три запроса
// составляют её транзакцию: прочитать актуальный статус под блокировкой
// строки → проверить переход (task.NextStatus, чистая функция) → записать
// новый статус и добавить task_events(status_change). Схема —
// orchestrator/migrations/00003_tasks_and_events.sql (не редактируется).
// Читает АКТУАЛЬНЫЙ статус задачи с блокировкой строки (FOR UPDATE) —
// единственный источник истины для Transition: вызывающая сторона НЕ
// передаёт текущий статус явно, что исключает TOCTOU-гонки между
// параллельными Transition для одной задачи. Блокировка также сериализует
// конкурентные вставки в task_events для этой задачи (см. InsertNextTaskEvent
// ниже) — без неё гонка за MAX(seq) была бы возможна.
func (q *Queries) GetTaskStatusForUpdate(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTaskStatusForUpdate, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const insertNextTaskEvent = `-- name: InsertNextTaskEvent :one
INSERT INTO task_events (task_id, seq, type, ref_event_id, payload_enc)
VALUES ($1, (SELECT COALESCE(MAX(seq), 0) + 1 FROM task_events WHERE task_id = $1), $2, $3, $4)
RETURNING id, task_id, seq, type, ref_event_id, payload_enc, created_at
`

type InsertNextTaskEventParams struct {
	TaskID     pgtype.UUID `json:"task_id"`
	Type       string      `json:"type"`
	RefEventID pgtype.UUID `json:"ref_event_id"`
	PayloadEnc []byte      `json:"payload_enc"`
}

// Вставляет запись журнала событий с автоматически вычисленным следующим seq
// в рамках задачи (FR F2) — безопасно под блокировкой строки tasks той же
// транзакции (см. GetTaskStatusForUpdate): конкурентные Transition для одной
// задачи сериализованы, поэтому гонка за MAX(seq) исключена. Transition
// (тикет 5.2) использует это для события type='status_change', ref_event_id
// всегда NULL (смена статуса не является ответом на вопрос/запрос, FR F2).
func (q *Queries) InsertNextTaskEvent(ctx context.Context, arg InsertNextTaskEventParams) (TaskEvent, error) {
	row := q.db.QueryRow(ctx, insertNextTaskEvent,
		arg.TaskID,
		arg.Type,
		arg.RefEventID,
		arg.PayloadEnc,
	)
	var i TaskEvent
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Seq,
		&i.Type,
		&i.RefEventID,
		&i.PayloadEnc,
		&i.CreatedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Меняет статус задачи; единственное место записи tasks.status. Вызывается
// только из Transition, ПОСЛЕ проверки допустимости перехода (NextStatus) и
// ВНУТРИ той же транзакции, что и GetTaskStatusForUpdate/InsertNextTaskEvent.
func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.Status)
	return err
}
