// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, integration_id, text_enc, idempotency_key)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, integration_id, text_enc, status, idempotency_key, created_at, updated_at
`

type CreateTaskParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	IntegrationID  pgtype.UUID `json:"integration_id"`
	TextEnc        []byte      `json:"text_enc"`
	IdempotencyKey *string     `json:"idempotency_key"`
}

// Вставляет новую задачу СО СТАТУСОМ ПО УМОЛЧАНИЮ 'created' (схема,
// migrations/00003) — переход в 'queued' и запись task_events(status_change)
// выполняются ОТДЕЛЬНО, сразу после вставки, через
// task.Transitioner.Transition(ctx, id, task.TriggerEnqueued): тикет 5.2
// сделал Transitioner единственной точкой смены tasks.status, поэтому
// обработчик POST /tasks (тикет 5.3) не пишет 'queued'/task_events напрямую.
// Коллизия (user_id, idempotency_key) — SQLSTATE 23505 (uq_tasks_idempotency);
// обработчик перехватывает её и обслуживает повтор через
// GetTaskByUserAndIdempotencyKey ниже (тикет 5.5, FR E7, §4 «Защита от
// двойной отправки»): существующая задача возвращается с 200, дубль не
// создаётся.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.IntegrationID,
		arg.TextEnc,
		arg.IdempotencyKey,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IntegrationID,
		&i.TextEnc,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByIDAndIntegration = `-- name: GetTaskByIDAndIntegration :one
SELECT id, user_id, integration_id, text_enc, status, idempotency_key, created_at, updated_at FROM tasks WHERE id = $1 AND integration_id = $2
`

type GetTaskByIDAndIntegrationParams struct {
	ID            pgtype.UUID `json:"id"`
	IntegrationID pgtype.UUID `json:"integration_id"`
}

// Ищет задачу по id, scoped по integration_id, а не по user_id (FR A4, I3,
// аналогия с GetTaskByIDAndUser выше) — используется на WS-пути (handleAgentQuestion,
// machine_ws.go, тикет 6.1), где аутентифицирована МАШИНА (integration_id), а не
// пользователь: проверяет, что вопрос агента адресован задаче именно ЭТОЙ
// интеграции, не давая одной машине инжектировать событие в чужую задачу.
func (q *Queries) GetTaskByIDAndIntegration(ctx context.Context, arg GetTaskByIDAndIntegrationParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByIDAndIntegration, arg.ID, arg.IntegrationID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IntegrationID,
		&i.TextEnc,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByIDAndUser = `-- name: GetTaskByIDAndUser :one
SELECT id, user_id, integration_id, text_enc, status, idempotency_key, created_at, updated_at FROM tasks WHERE id = $1 AND user_id = $2
`

type GetTaskByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Ищет задачу по id, owner-scoped прямо в SQL (FR A4, I3) — чужая/несуществующая
// задача неотличимы, единый 404 (тот же приём, что GetIntegrationByIDAndUser,
// тикет 2.2). Используется PostTasksIdAnswer (тикет 6.1) для проверки владения
// задачей перед применением ответа пользователя.
func (q *Queries) GetTaskByIDAndUser(ctx context.Context, arg GetTaskByIDAndUserParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByIDAndUser, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IntegrationID,
		&i.TextEnc,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByUserAndIdempotencyKey = `-- name: GetTaskByUserAndIdempotencyKey :one
SELECT id, user_id, integration_id, text_enc, status, idempotency_key, created_at, updated_at FROM tasks WHERE user_id = $1 AND idempotency_key = $2
`

type GetTaskByUserAndIdempotencyKeyParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	IdempotencyKey *string     `json:"idempotency_key"`
}

// Находит уже созданную задачу по (user_id, idempotency_key) после того, как
// INSERT в CreateTask упал на uq_tasks_idempotency (SQLSTATE 23505) — это и
// есть дедуп повторной постановки (тикет 5.5, FR E7): вместо создания дубля
// обработчик POST /tasks перечитывает уже существующую строку и возвращает
// её с 200, не трогая Transitioner и не публикуя task_assigned повторно (эта
// задача уже прошла весь путь при первой, не повторной, постановке).
func (q *Queries) GetTaskByUserAndIdempotencyKey(ctx context.Context, arg GetTaskByUserAndIdempotencyKeyParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByUserAndIdempotencyKey, arg.UserID, arg.IdempotencyKey)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IntegrationID,
		&i.TextEnc,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskStatusForUpdate = `-- name: GetTaskStatusForUpdate :one

SELECT status FROM tasks WHERE id = $1 FOR UPDATE
`

// tasks.sql — запросы FSM задач (тикет 5.2, FR E1).
//
// Назначение (бизнес): единственная точка смены tasks.status — функция
// Transition (orchestrator/internal/task/transition.go). Эти три запроса
// составляют её транзакцию: прочитать актуальный статус под блокировкой
// строки → проверить переход (task.NextStatus, чистая функция) → записать
// новый статус и добавить task_events(status_change). Схема —
// orchestrator/migrations/00003_tasks_and_events.sql (не редактируется).
// Читает АКТУАЛЬНЫЙ статус задачи с блокировкой строки (FOR UPDATE) —
// единственный источник истины для Transition: вызывающая сторона НЕ
// передаёт текущий статус явно, что исключает TOCTOU-гонки между
// параллельными Transition для одной задачи. Блокировка также сериализует
// конкурентные вставки в task_events для этой задачи (см. InsertNextTaskEvent
// ниже) — без неё гонка за MAX(seq) была бы возможна.
func (q *Queries) GetTaskStatusForUpdate(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTaskStatusForUpdate, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const insertNextTaskEvent = `-- name: InsertNextTaskEvent :one
INSERT INTO task_events (task_id, seq, type, ref_event_id, payload_enc)
VALUES ($1, (SELECT COALESCE(MAX(seq), 0) + 1 FROM task_events WHERE task_id = $1), $2, $3, $4)
RETURNING id, task_id, seq, type, ref_event_id, payload_enc, created_at
`

type InsertNextTaskEventParams struct {
	TaskID     pgtype.UUID `json:"task_id"`
	Type       string      `json:"type"`
	RefEventID pgtype.UUID `json:"ref_event_id"`
	PayloadEnc []byte      `json:"payload_enc"`
}

// Вставляет запись журнала событий с автоматически вычисленным следующим seq
// в рамках задачи (FR F2) — безопасно под блокировкой строки tasks той же
// транзакции (см. GetTaskStatusForUpdate): конкурентные Transition для одной
// задачи сериализованы, поэтому гонка за MAX(seq) исключена. Transition
// (тикет 5.2) использует это для события type='status_change', ref_event_id
// всегда NULL (смена статуса не является ответом на вопрос/запрос, FR F2).
func (q *Queries) InsertNextTaskEvent(ctx context.Context, arg InsertNextTaskEventParams) (TaskEvent, error) {
	row := q.db.QueryRow(ctx, insertNextTaskEvent,
		arg.TaskID,
		arg.Type,
		arg.RefEventID,
		arg.PayloadEnc,
	)
	var i TaskEvent
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Seq,
		&i.Type,
		&i.RefEventID,
		&i.PayloadEnc,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentQuestionEventsByTask = `-- name: ListAgentQuestionEventsByTask :many
SELECT id, task_id, seq, type, ref_event_id, payload_enc, created_at FROM task_events WHERE task_id = $1 AND type = 'agent_question' ORDER BY seq DESC
`

// Возвращает все события agent_question задачи, самые новые первыми — источник
// для сопоставления ответа пользователя (question_id из тела запроса) с
// конкретной записью task_events (её id становится ref_event_id ответа, тикет
// 6.1, FR F2). Сопоставление по question_id внутри payload_enc выполняется НА
// СТОРОНЕ GO (после json.Unmarshal), а не SQL-выражением вроде payload_enc::jsonb —
// payload_enc помимо джейсона со временем станет зашифрованным (TODO(11.1),
// как text_enc), и SQL-side JSON-экстракция тогда молча сломается.
func (q *Queries) ListAgentQuestionEventsByTask(ctx context.Context, taskID pgtype.UUID) ([]TaskEvent, error) {
	rows, err := q.db.Query(ctx, listAgentQuestionEventsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskEvent{}
	for rows.Next() {
		var i TaskEvent
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Seq,
			&i.Type,
			&i.RefEventID,
			&i.PayloadEnc,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommandApprovalRequestEventsByTask = `-- name: ListCommandApprovalRequestEventsByTask :many
SELECT id, task_id, seq, type, ref_event_id, payload_enc, created_at FROM task_events WHERE task_id = $1 AND type = 'command_approval_request' ORDER BY seq DESC
`

// Возвращает все события command_approval_request задачи, самые новые первыми —
// источник для сопоставления request_id из тела PostTasksIdApprove с конкретной
// записью task_events (её id становится ref_event_id решения, тикет 6.4, FR F3).
// Тот же приём, что и у ListAgentQuestionEventsByTask выше (тикет 6.1):
// сопоставление по request_id внутри payload_enc выполняется НА СТОРОНЕ GO
// (после json.Unmarshal), а не SQL-выражением вроде payload_enc::jsonb —
// payload_enc помимо джейсона со временем станет зашифрованным (TODO(11.1),
// как text_enc), и SQL-side JSON-экстракция тогда молча сломается.
func (q *Queries) ListCommandApprovalRequestEventsByTask(ctx context.Context, taskID pgtype.UUID) ([]TaskEvent, error) {
	rows, err := q.db.Query(ctx, listCommandApprovalRequestEventsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskEvent{}
	for rows.Next() {
		var i TaskEvent
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Seq,
			&i.Type,
			&i.RefEventID,
			&i.PayloadEnc,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningTasksWithStaleMachine = `-- name: ListRunningTasksWithStaleMachine :many
SELECT tasks.id FROM tasks
JOIN integrations ON integrations.id = tasks.integration_id
WHERE tasks.status IN ('running', 'waiting_user')
  AND (integrations.last_seen_at IS NULL OR integrations.last_seen_at < $1)
`

// «Зависание» машины (тикет 5.7, FR E5, protocol.md §6: STALE_THRESHOLD):
// находит активные (running/waiting_user) задачи, чья интеграция не подавала
// heartbeat дольше порога — cutoff считает вызывающая сторона
// (task.StaleWorker), здесь только сравнение с last_seen_at. last_seen_at
// IS NULL тоже считается «зависла» — защитный случай: MarkIntegrationOnline
// (queries/integrations.sql) всегда пишет last_seen_at ОДНОВРЕМЕННО с
// status='online', так что NULL означает «от этой машины вообще никогда не
// было heartbeat», а активная задача у такой интеграции быть не должна.
// Результат передаётся task.Transitioner.Transition(..., TriggerTimeout).
func (q *Queries) ListRunningTasksWithStaleMachine(ctx context.Context, lastSeenAt pgtype.Timestamptz) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRunningTasksWithStaleMachine, lastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleTasksWithRecoveredMachine = `-- name: ListStaleTasksWithRecoveredMachine :many
SELECT tasks.id FROM tasks
JOIN integrations ON integrations.id = tasks.integration_id
WHERE tasks.status = 'stale'
  AND integrations.last_seen_at IS NOT NULL
  AND integrations.last_seen_at >= $1
`

// Возврат «зависшей» машины (тикет 5.7, FR E5, protocol.md §6): находит
// задачи в статусе stale, чья интеграция снова свежо подавала heartbeat
// (last_seen_at не старше cutoff) — задача должна продолжиться, stale →
// running. Результат передаётся
// task.Transitioner.Transition(..., TriggerMachineRecovered).
func (q *Queries) ListStaleTasksWithRecoveredMachine(ctx context.Context, lastSeenAt pgtype.Timestamptz) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listStaleTasksWithRecoveredMachine, lastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitingUserTasksWithStaleQuestion = `-- name: ListWaitingUserTasksWithStaleQuestion :many
SELECT tasks.id AS task_id, tasks.user_id AS user_id, latest.id AS question_event_id, latest.created_at AS question_created_at
FROM tasks
JOIN LATERAL (
    SELECT id, created_at FROM task_events
    WHERE task_events.task_id = tasks.id AND task_events.type = 'agent_question'
    ORDER BY seq DESC
    LIMIT 1
) latest ON true
WHERE tasks.status = 'waiting_user'
  AND latest.created_at < $1
`

type ListWaitingUserTasksWithStaleQuestionRow struct {
	TaskID            pgtype.UUID        `json:"task_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	QuestionEventID   pgtype.UUID        `json:"question_event_id"`
	QuestionCreatedAt pgtype.Timestamptz `json:"question_created_at"`
}

// «Таймаут ответа» (тикет 6.7, FR F5): находит задачи в waiting_user, чей
// САМЫЙ ПОСЛЕДНИЙ (по seq) agent_question устарел дольше порога — cutoff
// считает вызывающая сторона (task.AnswerTimeoutWorker), здесь только
// сравнение с created_at найденной записи. JOIN LATERAL, а не просто
// MAX(created_at) по task_events, потому что вызывающей стороне нужен именно
// id КОНКРЕТНОЙ записи task_events (question_event_id) — для дедупликации
// повторных напоминаний по одному и тому же вопросу между тиками воркера, а
// не только временная метка последнего вопроса. Результат передаётся в
// notify.Notification (напоминание пользователю) и, при настроенном
// поведении auto_cancel, в task.Transitioner.Transition(...,
// TriggerCancelRequested).
func (q *Queries) ListWaitingUserTasksWithStaleQuestion(ctx context.Context, dollar_1 pgtype.Timestamptz) ([]ListWaitingUserTasksWithStaleQuestionRow, error) {
	rows, err := q.db.Query(ctx, listWaitingUserTasksWithStaleQuestion, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWaitingUserTasksWithStaleQuestionRow{}
	for rows.Next() {
		var i ListWaitingUserTasksWithStaleQuestionRow
		if err := rows.Scan(
			&i.TaskID,
			&i.UserID,
			&i.QuestionEventID,
			&i.QuestionCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Меняет статус задачи; единственное место записи tasks.status. Вызывается
// только из Transition, ПОСЛЕ проверки допустимости перехода (NextStatus) и
// ВНУТРИ той же транзакции, что и GetTaskStatusForUpdate/InsertNextTaskEvent.
func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.Status)
	return err
}
