// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (username, password_hash, is_admin)
VALUES ($1, $2, $3)
RETURNING id, username, password_hash, is_admin, created_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	IsAdmin      bool   `json:"is_admin"`
}

// users.sql — CRUD-запросы аккаунтов (FR A1, A2).
//
// Назначение (бизнес): доступ закрытый, регистрация только по токену (FR A1).
// Эти запросы — слой данных под регистрацию/логин (тикеты 1.2/1.3); бизнес-логика
// (проверка токена, хэширование пароля) живёт в сервисном слое, здесь — только SQL.
// Схема таблицы — orchestrator/migrations/00001_users_and_auth.sql (не редактируется).
// Создаёт аккаунт. password_hash — argon2id (FR I1), считается в сервисном слое.
// is_admin задаётся явно: первый/привилегированный аккаунт видит токен (FR A2).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash, arg.IsAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, is_admin, created_at FROM users
WHERE id = $1
`

// Аккаунт по id — для авторизованных запросов после валидации токена доступа.
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, is_admin, created_at FROM users
WHERE username = $1
`

// Аккаунт по уникальному username — путь логина (FR A3) и проверки занятости при
// регистрации (FR A1).
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const setUserAdmin = `-- name: SetUserAdmin :one
UPDATE users
SET is_admin = $2
WHERE id = $1
RETURNING id, username, password_hash, is_admin, created_at
`

type SetUserAdminParams struct {
	ID      pgtype.UUID `json:"id"`
	IsAdmin bool        `json:"is_admin"`
}

// Помечает аккаунт администратором (или снимает флаг). Админ видит токен
// регистрации в plaintext (FR A2).
func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserAdmin, arg.ID, arg.IsAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}
