// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Показать действующий токен регистрации
	// (GET /admin/registration-token)
	GetAdminRegistrationToken(w http.ResponseWriter, r *http.Request)
	// Логин
	// (POST /auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Выход (отзыв refresh)
	// (POST /auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// Обновление токенов
	// (POST /auth/refresh)
	PostAuthRefresh(w http.ResponseWriter, r *http.Request)
	// Регистрация по токену регистрации
	// (POST /auth/register)
	PostAuthRegister(w http.ResponseWriter, r *http.Request)
	// Обменять код привязки на привязку Telegram-аккаунта
	// (POST /channels/telegram/link)
	PostChannelsTelegramLink(w http.ResponseWriter, r *http.Request)
	// Сгенерировать код привязки Telegram
	// (POST /channels/telegram/link-code)
	PostChannelsTelegramLinkCode(w http.ResponseWriter, r *http.Request)
	// Обменять telegram_user_id на короткоживущий acting-токен (внутренний, только для бота)
	// (POST /channels/telegram/token)
	PostChannelsTelegramToken(w http.ResponseWriter, r *http.Request, params PostChannelsTelegramTokenParams)
	// Health-check
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Список интеграций пользователя
	// (GET /integrations)
	GetIntegrations(w http.ResponseWriter, r *http.Request)
	// Создать интеграцию (выдаёт UUID)
	// (POST /integrations)
	PostIntegrations(w http.ResponseWriter, r *http.Request)
	// Удалить интеграцию
	// (DELETE /integrations/{id})
	DeleteIntegrationsId(w http.ResponseWriter, r *http.Request, id IdPath, params DeleteIntegrationsIdParams)
	// Получить интеграцию
	// (GET /integrations/{id})
	GetIntegrationsId(w http.ResponseWriter, r *http.Request, id IdPath)
	// Редактировать имя/IP
	// (PATCH /integrations/{id})
	PatchIntegrationsId(w http.ResponseWriter, r *http.Request, id IdPath)
	// Точка подключения агента (WebSocket Upgrade)
	// (GET /machine/ws)
	GetMachineWs(w http.ResponseWriter, r *http.Request)
	// История задач
	// (GET /tasks)
	GetTasks(w http.ResponseWriter, r *http.Request, params GetTasksParams)
	// Поставить задачу
	// (POST /tasks)
	PostTasks(w http.ResponseWriter, r *http.Request, params PostTasksParams)
	// Карточка задачи
	// (GET /tasks/{id})
	GetTasksId(w http.ResponseWriter, r *http.Request, id IdPath)
	// Ответить на вопрос агента
	// (POST /tasks/{id}/answer)
	PostTasksIdAnswer(w http.ResponseWriter, r *http.Request, id IdPath)
	// Согласовать/отклонить команду
	// (POST /tasks/{id}/approve)
	PostTasksIdApprove(w http.ResponseWriter, r *http.Request, id IdPath)
	// Отменить задачу
	// (POST /tasks/{id}/cancel)
	PostTasksIdCancel(w http.ResponseWriter, r *http.Request, id IdPath)
	// Подтвердить завершение
	// (POST /tasks/{id}/confirm)
	PostTasksIdConfirm(w http.ResponseWriter, r *http.Request, id IdPath)
	// Журнал событий задачи
	// (GET /tasks/{id}/events)
	GetTasksIdEvents(w http.ResponseWriter, r *http.Request, id IdPath)
	// Отклонить результат (на доработку)
	// (POST /tasks/{id}/reject)
	PostTasksIdReject(w http.ResponseWriter, r *http.Request, id IdPath)
	// Точка подключения браузера (WebSocket Upgrade)
	// (GET /ws)
	GetWs(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Показать действующий токен регистрации
// (GET /admin/registration-token)
func (_ Unimplemented) GetAdminRegistrationToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Логин
// (POST /auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Выход (отзыв refresh)
// (POST /auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обновление токенов
// (POST /auth/refresh)
func (_ Unimplemented) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Регистрация по токену регистрации
// (POST /auth/register)
func (_ Unimplemented) PostAuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обменять код привязки на привязку Telegram-аккаунта
// (POST /channels/telegram/link)
func (_ Unimplemented) PostChannelsTelegramLink(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Сгенерировать код привязки Telegram
// (POST /channels/telegram/link-code)
func (_ Unimplemented) PostChannelsTelegramLinkCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Обменять telegram_user_id на короткоживущий acting-токен (внутренний, только для бота)
// (POST /channels/telegram/token)
func (_ Unimplemented) PostChannelsTelegramToken(w http.ResponseWriter, r *http.Request, params PostChannelsTelegramTokenParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health-check
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Список интеграций пользователя
// (GET /integrations)
func (_ Unimplemented) GetIntegrations(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать интеграцию (выдаёт UUID)
// (POST /integrations)
func (_ Unimplemented) PostIntegrations(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Удалить интеграцию
// (DELETE /integrations/{id})
func (_ Unimplemented) DeleteIntegrationsId(w http.ResponseWriter, r *http.Request, id IdPath, params DeleteIntegrationsIdParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить интеграцию
// (GET /integrations/{id})
func (_ Unimplemented) GetIntegrationsId(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Редактировать имя/IP
// (PATCH /integrations/{id})
func (_ Unimplemented) PatchIntegrationsId(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Точка подключения агента (WebSocket Upgrade)
// (GET /machine/ws)
func (_ Unimplemented) GetMachineWs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// История задач
// (GET /tasks)
func (_ Unimplemented) GetTasks(w http.ResponseWriter, r *http.Request, params GetTasksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Поставить задачу
// (POST /tasks)
func (_ Unimplemented) PostTasks(w http.ResponseWriter, r *http.Request, params PostTasksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Карточка задачи
// (GET /tasks/{id})
func (_ Unimplemented) GetTasksId(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Ответить на вопрос агента
// (POST /tasks/{id}/answer)
func (_ Unimplemented) PostTasksIdAnswer(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Согласовать/отклонить команду
// (POST /tasks/{id}/approve)
func (_ Unimplemented) PostTasksIdApprove(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Отменить задачу
// (POST /tasks/{id}/cancel)
func (_ Unimplemented) PostTasksIdCancel(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Подтвердить завершение
// (POST /tasks/{id}/confirm)
func (_ Unimplemented) PostTasksIdConfirm(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Журнал событий задачи
// (GET /tasks/{id}/events)
func (_ Unimplemented) GetTasksIdEvents(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Отклонить результат (на доработку)
// (POST /tasks/{id}/reject)
func (_ Unimplemented) PostTasksIdReject(w http.ResponseWriter, r *http.Request, id IdPath) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Точка подключения браузера (WebSocket Upgrade)
// (GET /ws)
func (_ Unimplemented) GetWs(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAdminRegistrationToken operation middleware
func (siw *ServerInterfaceWrapper) GetAdminRegistrationToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminRegistrationToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostChannelsTelegramLink operation middleware
func (siw *ServerInterfaceWrapper) PostChannelsTelegramLink(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostChannelsTelegramLink(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostChannelsTelegramLinkCode operation middleware
func (siw *ServerInterfaceWrapper) PostChannelsTelegramLinkCode(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostChannelsTelegramLinkCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostChannelsTelegramToken operation middleware
func (siw *ServerInterfaceWrapper) PostChannelsTelegramToken(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostChannelsTelegramTokenParams

	headers := r.Header

	// ------------- Required header parameter "X-Bot-Service-Secret" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Bot-Service-Secret")]; found {
		var XBotServiceSecret string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Bot-Service-Secret", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Bot-Service-Secret", valueList[0], &XBotServiceSecret, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Bot-Service-Secret", Err: err})
			return
		}

		params.XBotServiceSecret = XBotServiceSecret

	} else {
		err := fmt.Errorf("Header parameter X-Bot-Service-Secret is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Bot-Service-Secret", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostChannelsTelegramToken(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIntegrations operation middleware
func (siw *ServerInterfaceWrapper) GetIntegrations(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIntegrations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostIntegrations operation middleware
func (siw *ServerInterfaceWrapper) PostIntegrations(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostIntegrations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteIntegrationsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteIntegrationsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteIntegrationsIdParams

	// ------------- Optional query parameter "confirm" -------------

	err = runtime.BindQueryParameter("form", true, false, "confirm", r.URL.Query(), &params.Confirm)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "confirm", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteIntegrationsId(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIntegrationsId operation middleware
func (siw *ServerInterfaceWrapper) GetIntegrationsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIntegrationsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchIntegrationsId operation middleware
func (siw *ServerInterfaceWrapper) PatchIntegrationsId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchIntegrationsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMachineWs operation middleware
func (siw *ServerInterfaceWrapper) GetMachineWs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMachineWs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTasks operation middleware
func (siw *ServerInterfaceWrapper) GetTasks(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTasksParams

	// ------------- Optional query parameter "integration_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "integration_id", r.URL.Query(), &params.IntegrationId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "integration_id", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTasks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTasks operation middleware
func (siw *ServerInterfaceWrapper) PostTasks(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PostTasksParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTasks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTasksId operation middleware
func (siw *ServerInterfaceWrapper) GetTasksId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTasksId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTasksIdAnswer operation middleware
func (siw *ServerInterfaceWrapper) PostTasksIdAnswer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTasksIdAnswer(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTasksIdApprove operation middleware
func (siw *ServerInterfaceWrapper) PostTasksIdApprove(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTasksIdApprove(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTasksIdCancel operation middleware
func (siw *ServerInterfaceWrapper) PostTasksIdCancel(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTasksIdCancel(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTasksIdConfirm operation middleware
func (siw *ServerInterfaceWrapper) PostTasksIdConfirm(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTasksIdConfirm(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTasksIdEvents operation middleware
func (siw *ServerInterfaceWrapper) GetTasksIdEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTasksIdEvents(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTasksIdReject operation middleware
func (siw *ServerInterfaceWrapper) PostTasksIdReject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id IdPath

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTasksIdReject(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWs operation middleware
func (siw *ServerInterfaceWrapper) GetWs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/registration-token", wrapper.GetAdminRegistrationToken)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.PostAuthRefresh)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.PostAuthRegister)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/channels/telegram/link", wrapper.PostChannelsTelegramLink)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/channels/telegram/link-code", wrapper.PostChannelsTelegramLinkCode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/channels/telegram/token", wrapper.PostChannelsTelegramToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/integrations", wrapper.GetIntegrations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/integrations", wrapper.PostIntegrations)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/integrations/{id}", wrapper.DeleteIntegrationsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/integrations/{id}", wrapper.GetIntegrationsId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/integrations/{id}", wrapper.PatchIntegrationsId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/machine/ws", wrapper.GetMachineWs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tasks", wrapper.GetTasks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tasks", wrapper.PostTasks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tasks/{id}", wrapper.GetTasksId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tasks/{id}/answer", wrapper.PostTasksIdAnswer)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tasks/{id}/approve", wrapper.PostTasksIdApprove)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tasks/{id}/cancel", wrapper.PostTasksIdCancel)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tasks/{id}/confirm", wrapper.PostTasksIdConfirm)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tasks/{id}/events", wrapper.GetTasksIdEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tasks/{id}/reject", wrapper.PostTasksIdReject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ws", wrapper.GetWs)
	})

	return r
}
