// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ChannelLinkChannel.
const (
	Telegram ChannelLinkChannel = "telegram"
)

// Defines values for IntegrationStatus.
const (
	IntegrationStatusOffline IntegrationStatus = "offline"
	IntegrationStatusOnline  IntegrationStatus = "online"
)

// Defines values for IntegrationWithSecretStatus.
const (
	IntegrationWithSecretStatusOffline IntegrationWithSecretStatus = "offline"
	IntegrationWithSecretStatusOnline  IntegrationWithSecretStatus = "online"
)

// Defines values for TaskEventType.
const (
	TaskEventTypeAgentCompleted         TaskEventType = "agent_completed"
	TaskEventTypeAgentProgress          TaskEventType = "agent_progress"
	TaskEventTypeAgentQuestion          TaskEventType = "agent_question"
	TaskEventTypeCommandApprovalRequest TaskEventType = "command_approval_request"
	TaskEventTypeError                  TaskEventType = "error"
	TaskEventTypeStatusChange           TaskEventType = "status_change"
	TaskEventTypeUserAnswer             TaskEventType = "user_answer"
	TaskEventTypeUserDecision           TaskEventType = "user_decision"
)

// Defines values for TaskStatus.
const (
	AwaitingConfirm TaskStatus = "awaiting_confirm"
	Cancelled       TaskStatus = "cancelled"
	Completed       TaskStatus = "completed"
	Created         TaskStatus = "created"
	Failed          TaskStatus = "failed"
	Queued          TaskStatus = "queued"
	Running         TaskStatus = "running"
	Stale           TaskStatus = "stale"
	WaitingUser     TaskStatus = "waiting_user"
)

// Defines values for PostTasksIdApproveJSONBodyDecision.
const (
	Approve PostTasksIdApproveJSONBodyDecision = "approve"
	Reject  PostTasksIdApproveJSONBodyDecision = "reject"
)

// ChannelLink Привязка внешнего канала к аккаунту (FR D3).
type ChannelLink struct {
	Channel   *ChannelLinkChannel `json:"channel,omitempty"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`

	// ExternalId telegram_user_id привязанного Telegram-аккаунта
	ExternalId *string `json:"external_id,omitempty"`
}

// ChannelLinkChannel defines model for ChannelLink.Channel.
type ChannelLinkChannel string

// ChannelLinkRequest Тело POST /channels/telegram/link (FR D3, тикет 10.2).
type ChannelLinkRequest struct {
	// Code Одноразовый код привязки из POST /channels/telegram/link-code (тикет 9.6).
	Code string `json:"code"`

	// TelegramUserId Telegram user id отправителя /start <code> (числовой id Telegram, передаётся строкой — channel_links.external_id хранит идентификатор как TEXT, канало-агностично).
	TelegramUserId string `json:"telegram_user_id"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Integration defines model for Integration.
type Integration struct {
	CreatedAt  *time.Time          `json:"created_at,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	IpHint     *string             `json:"ip_hint"`
	LastSeenAt *time.Time          `json:"last_seen_at"`
	Name       *string             `json:"name,omitempty"`

	// Status FR B4
	Status *IntegrationStatus `json:"status,omitempty"`
}

// IntegrationStatus FR B4
type IntegrationStatus string

// IntegrationCreate defines model for IntegrationCreate.
type IntegrationCreate struct {
	// IpHint Опциональная доп. проверка IP (FR B3)
	IpHint *string `json:"ip_hint"`
	Name   string  `json:"name"`
}

// IntegrationUpdate defines model for IntegrationUpdate.
type IntegrationUpdate struct {
	IpHint *string `json:"ip_hint"`
	Name   *string `json:"name,omitempty"`
}

// IntegrationWithSecret defines model for IntegrationWithSecret.
type IntegrationWithSecret struct {
	CreatedAt  *time.Time          `json:"created_at,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	IpHint     *string             `json:"ip_hint"`
	LastSeenAt *time.Time          `json:"last_seen_at"`
	Name       *string             `json:"name,omitempty"`

	// Status FR B4
	Status *IntegrationWithSecretStatus `json:"status,omitempty"`

	// Uuid Секрет для аутентификации машины (FR B2). Показывается владельцу.
	Uuid *openapi_types.UUID `json:"uuid,omitempty"`
}

// IntegrationWithSecretStatus FR B4
type IntegrationWithSecretStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Password          string `json:"password"`
	RegistrationToken string `json:"registration_token"`
	Username          string `json:"username"`
}

// Task defines model for Task.
type Task struct {
	CreatedAt     *time.Time          `json:"created_at,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	IntegrationId *openapi_types.UUID `json:"integration_id,omitempty"`

	// Status Статусы FSM, см. docs/Жизненный цикл задачи.md
	Status *TaskStatus `json:"status,omitempty"`

	// Text Текст запроса на момент создания задачи; неизменяем (FR H3).
	Text      *string    `json:"text,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// TaskCreate defines model for TaskCreate.
type TaskCreate struct {
	IntegrationId openapi_types.UUID `json:"integration_id"`

	// Text Текст запроса. Неизменяем после создания задачи (FR H3) — API для редактирования текста существующей задачи нет. Чтобы «исправить» уже отправленный запрос, нужно создать новую задачу отдельным POST /tasks (свой Idempotency-Key) — это отдельное действие («повтор»), не затрагивающее статус/журнал уже существующей задачи.
	Text string `json:"text"`
}

// TaskEvent Элемент журнала задачи (FR H1, аудит F4)
type TaskEvent struct {
	CreatedAt *time.Time              `json:"created_at,omitempty"`
	Id        *openapi_types.UUID     `json:"id,omitempty"`
	Payload   *map[string]interface{} `json:"payload,omitempty"`

	// Seq Порядковый номер в рамках задачи
	Seq  *int           `json:"seq,omitempty"`
	Type *TaskEventType `json:"type,omitempty"`
}

// TaskEventType defines model for TaskEvent.Type.
type TaskEventType string

// TaskStatus Статусы FSM, см. docs/Жизненный цикл задачи.md
type TaskStatus string

// TelegramActingToken Короткоживущий access-JWT, действующий от имени пользователя, к которому привязан telegram_user_id (FR D1, тикет 10.3). Тот же формат и TTL, что и access-токен POST /auth/login (FR A3) — используется боту как Bearer в дальнейших вызовах единого API.
type TelegramActingToken struct {
	AccessToken *string    `json:"access_token,omitempty"`
	ExpiresAt   *time.Time `json:"expires_at,omitempty"`
}

// TelegramActingTokenRequest Тело POST /channels/telegram/token (FR D1, тикет 10.3).
type TelegramActingTokenRequest struct {
	// TelegramUserId Telegram user id отправителя апдейта (та же строка, что и в ChannelLinkRequest).
	TelegramUserId string `json:"telegram_user_id"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn TTL access-токена
	ExpiresIn    *int   `json:"expires_in,omitempty"`
	RefreshToken string `json:"refresh_token"`
}

// IdPath defines model for IdPath.
type IdPath = openapi_types.UUID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// PostAuthLogoutJSONBody defines parameters for PostAuthLogout.
type PostAuthLogoutJSONBody struct {
	RefreshToken string `json:"refresh_token"`
}

// PostAuthRefreshJSONBody defines parameters for PostAuthRefresh.
type PostAuthRefreshJSONBody struct {
	RefreshToken string `json:"refresh_token"`
}

// PostChannelsTelegramTokenParams defines parameters for PostChannelsTelegramToken.
type PostChannelsTelegramTokenParams struct {
	XBotServiceSecret string `json:"X-Bot-Service-Secret"`
}

// DeleteIntegrationsIdParams defines parameters for DeleteIntegrationsId.
type DeleteIntegrationsIdParams struct {
	Confirm *bool `form:"confirm,omitempty" json:"confirm,omitempty"`
}

// GetTasksParams defines parameters for GetTasks.
type GetTasksParams struct {
	IntegrationId *openapi_types.UUID `form:"integration_id,omitempty" json:"integration_id,omitempty"`
	Status        *TaskStatus         `form:"status,omitempty" json:"status,omitempty"`
}

// PostTasksParams defines parameters for PostTasks.
type PostTasksParams struct {
	// IdempotencyKey Ключ дедупликации постановки задачи (FR E7).
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// PostTasksIdAnswerJSONBody defines parameters for PostTasksIdAnswer.
type PostTasksIdAnswerJSONBody struct {
	QuestionId openapi_types.UUID `json:"question_id"`
	Text       string             `json:"text"`
}

// PostTasksIdApproveJSONBody defines parameters for PostTasksIdApprove.
type PostTasksIdApproveJSONBody struct {
	Decision  PostTasksIdApproveJSONBodyDecision `json:"decision"`
	RequestId openapi_types.UUID                 `json:"request_id"`
}

// PostTasksIdApproveJSONBodyDecision defines parameters for PostTasksIdApprove.
type PostTasksIdApproveJSONBodyDecision string

// PostTasksIdRejectJSONBody defines parameters for PostTasksIdReject.
type PostTasksIdRejectJSONBody struct {
	Comment *string `json:"comment,omitempty"`
}

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthLogoutJSONRequestBody defines body for PostAuthLogout for application/json ContentType.
type PostAuthLogoutJSONRequestBody PostAuthLogoutJSONBody

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody PostAuthRefreshJSONBody

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// PostChannelsTelegramLinkJSONRequestBody defines body for PostChannelsTelegramLink for application/json ContentType.
type PostChannelsTelegramLinkJSONRequestBody = ChannelLinkRequest

// PostChannelsTelegramTokenJSONRequestBody defines body for PostChannelsTelegramToken for application/json ContentType.
type PostChannelsTelegramTokenJSONRequestBody = TelegramActingTokenRequest

// PostIntegrationsJSONRequestBody defines body for PostIntegrations for application/json ContentType.
type PostIntegrationsJSONRequestBody = IntegrationCreate

// PatchIntegrationsIdJSONRequestBody defines body for PatchIntegrationsId for application/json ContentType.
type PatchIntegrationsIdJSONRequestBody = IntegrationUpdate

// PostTasksJSONRequestBody defines body for PostTasks for application/json ContentType.
type PostTasksJSONRequestBody = TaskCreate

// PostTasksIdAnswerJSONRequestBody defines body for PostTasksIdAnswer for application/json ContentType.
type PostTasksIdAnswerJSONRequestBody PostTasksIdAnswerJSONBody

// PostTasksIdApproveJSONRequestBody defines body for PostTasksIdApprove for application/json ContentType.
type PostTasksIdApproveJSONRequestBody PostTasksIdApproveJSONBody

// PostTasksIdRejectJSONRequestBody defines body for PostTasksIdReject for application/json ContentType.
type PostTasksIdRejectJSONRequestBody PostTasksIdRejectJSONBody
